In [1]:
import pandas as pd
import numpy as np

In [2]:
credits=pd.read_csv("D:/Shubham/DataSets For Practice/tmdb_5000_credits.csv")
movies=pd.read_csv("D:/Shubham/DataSets For Practice/tmdb_5000_movies.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.shape

(4803, 4)

In [6]:
# now we have to merge this two datasets into single

movies = movies.merge(credits,on='title')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
movies.shape

(4809, 23)

In [9]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [10]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.duplicated().sum()

0

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# we want this in this format [action,adventures,fantacy,science friction]

In [16]:
# we want this string conver into list

import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [17]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [18]:
movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies['keywords'] = movies['keywords'].apply(convert)

In [20]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
# we need only first 3 cast of movies for recommender

def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [22]:
movies['cast'] = movies['cast'].apply(convert3)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [24]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [25]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [26]:
# because overview column is in string format we have to convert it into list
movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
2975,88641,There Goes My Baby,"[A, group, of, high, school, seniors, meets, i...","[Drama, Comedy]",[],"[Dermot Mulroney, Ricky Schroder, Kelli Williams]",[Floyd Mutrux]
649,76493,The Dictator,"[The, heroic, story, of, a, dictator, who, ris...",[Comedy],[kurdish],"[Sacha Baron Cohen, Sayed Badreya, Aasif Mandvi]",[Larry Charles]
3706,1429,25th Hour,"[The, filmed, adaptation, from, David, Benioff...","[Crime, Drama]","[prison, prisoner, dream, drug dealer, nightcl...","[Edward Norton, Philip Seymour Hoffman, Barry ...",[Spike Lee]
1557,9880,The Princess Diaries,"[A, socially, awkward, but, very, bright, 15-y...","[Comedy, Family, Romance]","[heir to the throne, grandmother granddaughter...","[Anne Hathaway, Julie Andrews, Heather Matarazzo]",[Garry Marshall]
486,274854,The Last Witch Hunter,"[The, modern, world, holds, many, secrets,, bu...","[Fantasy, Action, Adventure]","[new york, witch, uprising, witch hunter]","[Vin Diesel, Rose Leslie, Elijah Wood]",[Breck Eisner]

we want ['Matt Damon']=['MattDamon']
      ['Sam Worthington]=['SamWorthington]

In [27]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(' ','') for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(' ','') for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(' ','') for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(' ','') for i in x])

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [29]:
# add this 5 column into one cloumn

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [30]:
new_df = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [31]:
# we used this function to convert list into string

new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):               # stem will convert similar words into root words 
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
        return ''.join(y)

new_df['tags']=new_df['tags'].apply(stem)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [33]:
 vector=cv.fit_transform(new_df['tags']).toarray()

In [34]:
cv.get_feature_names()

C:\Users\dell\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'ann',
 'anna',
 'annabelle',
 'annafaris',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymity',
 'anonymous',
 'answer',
 'answers',
 'ant',
 'antarctic',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeology',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atheist',
 'athlete',
 'atlantic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breast',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colombia',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'communist',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 ...]

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
similarity = cosine_similarity(vector)

In [43]:
list(enumerate(similarity[1]))  # enumeratate function used for to not change the index of movie

[(0, 0.08964214570007951),
 (1, 0.9999999999999999),
 (2, 0.06350006350009525),
 (3, 0.020833333333333332),
 (4, 0.08183170883849714),
 (5, 0.12376844287208427),
 (6, 0.024282146558931603),
 (7, 0.13176156917368248),
 (8, 0.06681531047810609),
 (9, 0.0808745799025788),
 (10, 0.09231861823449955),
 (11, 0.05661385170722978),
 (12, 0.4342995181076895),
 (13, 0.09901475429766741),
 (14, 0.11952286093343935),
 (15, 0.0799502686333539),
 (16, 0.08603090020146066),
 (17, 0.26940795304016235),
 (18, 0.04682929057908469),
 (19, 0.11410886614690958),
 (20, 0.08111071056538126),
 (21, 0.06565321642986127),
 (22, 0.07216878364870323),
 (23, 0.10206207261596575),
 (24, 0.14731391274719738),
 (25, 0.1216660658480719),
 (26, 0.11952286093343935),
 (27, 0.073543550676819),
 (28, 0.06565321642986127),
 (29, 0.04950737714883371),
 (30, 0.1275775907699572),
 (31, 0.10022296571715912),
 (32, 0.09534625892455922),
 (33, 0.11058146711617285),
 (34, 0.036084391824351615),
 (35, 0.11572751247156893),
 (36, 0.08603090020146065),
 (37, 0.05892556509887895),
 (38, 0.10963225241337865),
 (39, 0.06154574548966637),
 (40, 0.05892556509887895),
 (41, 0.07654655446197431),
 (42, 0.0),
 (43, 0.05103103630798288),
 (44, 0.042874646285627205),
 (45, 0.07150969419341942),
 (46, 0.12309149097933274),
 (47, 0.09053574604251853),
 (48, 0.0944911182523068),
 (49, 0.03340765523905304),
 (50, 0.09682458365518541),
 (51, 0.04490132550669372),
 (52, 0.09095085938862485),
 (53, 0.05157106231293967),
 (54, 0.036860489038724284),
 (55, 0.08006407690254355),
 (56, 0.0753778361444409),
 (57, 0.09095085938862485),
 (58, 0.07426106572325056),
 (59, 0.10489766978708612),
 (60, 0.0),
 (61, 0.1507556722888818),
 (62, 0.12862393885688161),
 (63, 0.04811252243246881),
 (64, 0.032826608214930636),
 (65, 0.02192645048267573),
 (66, 0.13032150878567172),
 (67, 0.062499999999999986),
 (68, 0.10400628679223047),
 (69, 0.054410718758250876),
 (70, 0.05661385170722978),
 (71, 0.11470786693528087),
 (72, 0.09682458365518541),
 (73, 0.039528470752104736),
 (74, 0.026352313834736494),
 (75, 0.1936491673103708),
 (76, 0.05455447255899809),
 (77, 0.04651302547095317),
 (78, 0.05590169943749474),
 (79, 0.10910894511799618),
 (80, 0.036084391824351615),
 (81, 0.08164965809277258),
 (82, 0.029061909685954818),
 (83, 0.0773565934694095),
 (84, 0.10879853497231112),
 (85, 0.11118739749916517),
 (86, 0.06154574548966637),
 (87, 0.030316953129541614),
 (88, 0.09525009525014287),
 (89, 0.032141217326661246),
 (90, 0.10206207261596575),
 (91, 0.10022296571715913),
 (92, 0.07426106572325056),
 (93, 0.05270462766947299),
 (94, 0.1386750490563073),
 (95, 0.026064301757134343),
 (96, 0.09374999999999997),
 (97, 0.07819290527140303),
 (98, 0.15386436372416593),
 (99, 0.062499999999999986),
 (100, 0.03857583749052298),
 (101, 0.06154574548966637),
 (102, 0.04682929057908469),
 (103, 0.09284766908852592),
 (104, 0.15386436372416593),
 (105, 0.11306675421666135),
 (106, 0.11707322644771173),
 (107, 0.07216878364870322),
 (108, 0.05050762722761053),
 (109, 0.16666666666666666),
 (110, 0.02551551815399144),
 (111, 0.06454972243679027),
 (112, 0.06350006350009525),
 (113, 0.05521576303742327),
 (114, 0.05521576303742327),
 (115, 0.11322770341445956),
 (116, 0.029880715233359837),
 (117, 0.09525009525014289),
 (118, 0.018430244519362142),
 (119, 0.05103103630798288),
 (120, 0.0),
 (121, 0.09525009525014289),
 (122, 0.13363062095621217),
 (123, 0.05103103630798288),
 (124, 0.07150969419341942),
 (125, 0.03340765523905304),
 (126, 0.12126781251816646),
 (127, 0.10138838820672656),
 (128, 0.03227486121839514),
 (129, 0.1656472891122698),
 (130, 0.03340765523905304),
 (131, 0.08838834764831843),
 (132, 0.07150969419341942),
 (133, 0.06933752452815364),
 (134, 0.07071067811865475),
 (135, 0.0),
 (136, 0.0799502686333539),
 (137, 0.017948953965443454),
 (138, 0.1433848336691011),
 (139, 0.09053574604251853),
 (140, 0.026650089544451302),
 (141, 0.039528470752104736),
 (142, 0.10206207261596575),
 (143, 0.12141073279465803),
 (144, 0.058123819371909635),
 (145, 0.0472455591261534),
 (146, 0.018042195912175808),
 (147, 0.06565321642986127),
 (148, 0.07372097807744857),
 (149, 0.0679018095318889),
 (150, 0.08770580193070292),
 (151, 0.08574929257125441),
 (152, 0.06681531047810609),
 (153, 0.045267873021259265),
 (154, 0.03466876226407682),
 (155, 0.0),
 (156, 0.04642383454426296),
 (157, 0.07372097807744857),
 (158, 0.0799502686333539),
 (159, 0.07071067811865475),
 (160, 0.06083303292403594),
 (161, 0.036860489038724284),
 (162, 0.07715167498104596),
 (163, 0.02830692585361489),
 (164, 0.09847982464479191),
 (165, 0.026064301757134343),
 (166, 0.062499999999999986),
 (167, 0.10825317547305485),
 (168, 0.11180339887498948),
 (169, 0.09999999999999999),
 (170, 0.04811252243246881),
 (171, 0.12309149097933274),
 (172, 0.07905694150420947),
 (173, 0.02551551815399144),
 (174, 0.058123819371909635),
 (175, 0.053916386601719206),
 (176, 0.06454972243679027),
 (177, 0.0),
 (178, 0.0808745799025788),
 (179, 0.039528470752104736),
 (180, 0.024999999999999998),
 (181, 0.049029033784546004),
 (182, 0.08385254915624211),
 (183, 0.05856516070822727),
 (184, 0.05455447255899809),
 (185, 0.029061909685954818),
 (186, 0.04256282653793742),
 (187, 0.20623947784607635),
 (188, 0.0236227795630767),
 (189, 0.042874646285627205),
 (190, 0.15348515337873012),
 (191, 0.10783277320343841),
 (192, 0.026064301757134343),
 (193, 0.11410886614690958),
 (194, 0.0),
 (195, 0.06804138174397717),
 (196, 0.06154574548966637),
 (197, 0.07654655446197431),
 (198, 0.062499999999999986),
 (199, 0.269659685815003),
 (200, 0.04055535528269063),
 (201, 0.0),
 (202, 0.036084391824351615),
 (203, 0.06154574548966637),
 (204, 0.02795084971874737),
 (205, 0.08574929257125441),
 (206, 0.08111071056538126),
 (207, 0.059761430466719674),
 (208, 0.13258252147247765),
 (209, 0.08111071056538126),
 (210, 0.057353933467640436),
 (211, 0.028676966733820218),
 (212, 0.053300179088902604),
 (213, 0.04564354645876383),
 (214, 0.06063390625908323),
 (215, 0.10314212462587934),
 (216, 0.2041241452319315),
 (217, 0.07284643967679481),
 (218, 0.044194173824159216),
 (219, 0.06933752452815364),
 (220, 0.09847982464479191),
 (221, 0.025785531156469834),
 (222, 0.0944911182523068),
 (223, 0.058123819371909635),
 (224, 0.022097086912079608),
 (225, 0.05455447255899809),
 (226, 0.062499999999999986),
 (227, 0.06454972243679027),
 (228, 0.07905694150420949),
 (229, 0.0413802944301184),
 (230, 0.04642383454426296),
 (231, 0.0),
 (232, 0.12499999999999997),
 (233, 0.0753778361444409),
 (234, 0.0944911182523068),
 (235, 0.06350006350009525),
 (236, 0.034020690871988585),
 (237, 0.07372097807744857),
 (238, 0.06681531047810609),
 (239, 0.02321191727213148),
 (240, 0.0799502686333539),
 (241, 0.09374999999999997),
 (242, 0.09847982464479191),
 (243, 0.07819290527140303),
 (244, 0.032826608214930636),
 (245, 0.06350006350009525),
 (246, 0.06904309634237427),
 (247, 0.036084391824351615),
 (248, 0.04950737714883371),
 (249, 0.0753778361444409),
 (250, 0.036860489038724284),
 (251, 0.0),
 (252, 0.04767312946227961),
 (253, 0.04602873089491617),
 (254, 0.058123819371909635),
 (255, 0.029462782549439476),
 (256, 0.042874646285627205),
 (257, 0.06063390625908323),
 (258, 0.024514516892273002),
 (259, 0.06681531047810609),
 (260, 0.09847982464479191),
 (261, 0.026650089544451302),
 (262, 0.10425720702853737),
 (263, 0.11058146711617285),
 (264, 0.0),
 (265, 0.030772872744833184),
 (266, 0.029061909685954818),
 (267, 0.11858541225631421),
 (268, 0.028676966733820218),
 (269, 0.0),
 (270, 0.0808745799025788),
 (271, 0.11043152607484653),
 (272, 0.0),
 (273, 0.0773565934694095),
 (274, 0.033709993123162106),
 (275, 0.032826608214930636),
 (276, 0.1414213562373095),
 (277, 0.04602873089491617),
 (278, 0.053916386601719206),
 (279, 0.026958193300859603),
 (280, 0.062499999999999986),
 (281, 0.02551551815399144),
 (282, 0.03227486121839514),
 (283, 0.030316953129541614),
 (284, 0.021128856368212913),
 (285, 0.04767312946227961),
 (286, 0.07086833868923009),
 (287, 0.028676966733820218),
 (288, 0.0),
 (289, 0.05270462766947299),
 (290, 0.07071067811865475),
 (291, 0.05892556509887895),
 (292, 0.10606601717798213),
 (293, 0.03340765523905304),
 (294, 0.09374999999999997),
 (295, 0.057353933467640436),
 (296, 0.04195906791483445),
 (297, 0.025253813613805264),
 (298, 0.0),
 (299, 0.04351941398892445),
 (300, 0.05590169943749474),
 (301, 0.021128856368212913),
 (302, 0.06350006350009525),
 (303, 0.030316953129541614),
 (304, 0.0753778361444409),
 (305, 0.06735198826004057),
 (306, 0.032826608214930636),
 (307, 0.03646624787447363),
 (308, 0.036860489038724284),
 (309, 0.06933752452815364),
 (310, 0.16960013132499202),
 (311, 0.027277236279499045),
 (312, 0.08603090020146065),
 (313, 0.0),
 (314, 0.0),
 (315, 0.09525009525014289),
 (316, 0.02551551815399144),
 (317, 0.0),
 (318, 0.0),
 (319, 0.03768891807222045),
 (320, 0.035355339059327376),
 (321, 0.0),
 (322, 0.08718572905786445),
 (323, 0.03466876226407682),
 (324, 0.027607881518711633),
 (325, 0.11572751247156893),
 (326, 0.030772872744833184),
 (327, 0.06063390625908323),
 (328, 0.03227486121839514),
 (329, 0.11624763874381927),
 (330, 0.1178511301977579),
 (331, 0.052128603514268686),
 (332, 0.08964214570007951),
 (333, 0.03227486121839514),
 (334, 0.11180339887498948),
 (335, 0.029462782549439476),
 (336, 0.07715167498104596),
 (337, 0.025253813613805264),
 (338, 0.0),
 (339, 0.059761430466719674),
 (340, 0.16366341767699427),
 (341, 0.06454972243679027),
 (342, 0.10206207261596573),
 (343, 0.0),
 (344, 0.032826608214930636),
 (345, 0.04950737714883371),
 (346, 0.0),
 (347, 0.0),
 (348, 0.07071067811865475),
 (349, 0.16137430609197567),
 (350, 0.057353933467640436),
 (351, 0.0),
 (352, 0.06154574548966637),
 (353, 0.024999999999999998),
 (354, 0.0),
 (355, 0.06293860187225167),
 (356, 0.06454972243679027),
 (357, 0.0),
 (358, 0.03466876226407682),
 (359, 0.10825317547305485),
 (360, 0.0),
 (361, 0.05892556509887895),
 (362, 0.034020690871988585),
 (363, 0.04767312946227961),
 (364, 0.05455447255899809),
 (365, 0.0),
 (366, 0.031249999999999993),
 (367, 0.0),
 (368, 0.07071067811865475),
 (369, 0.09682458365518541),
 (370, 0.05892556509887895),
 (371, 0.053916386601719206),
 (372, 0.02795084971874737),
 (373, 0.0),
 (374, 0.06963575181639443),
 (375, 0.022633936510629633),
 (376, 0.05103103630798288),
 (377, 0.0),
 (378, 0.03340765523905304),
 (379, 0.055901699437494734),
 (380, 0.0),
 (381, 0.0944911182523068),
 (382, 0.0),
 (383, 0.053916386601719206),
 (384, 0.06804138174397717),
 (385, 0.03227486121839514),
 (386, 0.07576144084141578),
 (387, 0.028676966733820218),
 (388, 0.02795084971874737),
 (389, 0.1414213562373095),
 (390, 0.029462782549439476),
 (391, 0.042874646285627205),
 (392, 0.09847982464479191),
 (393, 0.029462782549439476),
 (394, 0.027277236279499045),
 (395, 0.0),
 (396, 0.024753688574416854),
 (397, 0.029061909685954818),
 (398, 0.05270462766947299),
 (399, 0.026958193300859603),
 (400, 0.07216878364870323),
 (401, 0.0),
 (402, 0.06454972243679027),
 (403, 0.1380861926847485),
 (404, 0.0),
 (405, 0.03227486121839514),
 (406, 0.0),
 (407, 0.05455447255899809),
 (408, 0.036860489038724284),
 (409, 0.035355339059327376),
 (410, 0.05270462766947299),
 (411, 0.09231861823449955),
 (412, 0.1332504477222565),
 (413, 0.058123819371909635),
 (414, 0.03466876226407682),
 (415, 0.018633899812498245),
 (416, 0.05892556509887895),
 (417, 0.035355339059327376),
 (418, 0.039528470752104736),
 (419, 0.0799502686333539),
 (420, 0.10783277320343841),
 (421, 0.0),
 (422, 0.03857583749052298),
 (423, 0.05455447255899809),
 (424, 0.042257712736425826),
 (425, 0.04950737714883371),
 (426, 0.064790131918602),
 (427, 0.030772872744833184),
 (428, 0.0413802944301184),
 (429, 0.0),
 (430, 0.0),
 (431, 0.053916386601719206),
 (432, 0.05270462766947299),
 (433, 0.03466876226407682),
 (434, 0.029061909685954818),
 (435, 0.08333333333333333),
 (436, 0.0),
 (437, 0.06063390625908323),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.02551551815399144),
 (443, 0.06154574548966637),
 (444, 0.026958193300859603),
 (445, 0.0),
 (446, 0.026958193300859603),
 (447, 0.024999999999999998),
 (448, 0.05455447255899809),
 (449, 0.030316953129541614),
 (450, 0.0),
 (451, 0.027607881518711633),
 (452, 0.03340765523905304),
 (453, 0.02795084971874737),
 (454, 0.025785531156469834),
 (455, 0.025785531156469834),
 (456, 0.024514516892273002),
 (457, 0.09095085938862485),
 (458, 0.024753688574416854),
 (459, 0.03768891807222045),
 (460, 0.0),
 (461, 0.12166606584807188),
 (462, 0.0206901472150592),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.07372097807744857),
 (467, 0.07150969419341942),
 (468, 0.06350006350009525),
 (469, 0.049029033784546004),
 (470, 0.05157106231293967),
 (471, 0.11624763874381927),
 (472, 0.1178511301977579),
 (473, 0.053300179088902604),
 (474, 0.0),
 (475, 0.07150969419341942),
 (476, 0.03768891807222045),
 (477, 0.0),
 (478, 0.041666666666666664),
 (479, 0.0397778642087865),
 (480, 0.05455447255899809),
 (481, 0.0),
 (482, 0.0),
 (483, 0.10206207261596575),
 (484, 0.036084391824351615),
 (485, 0.05892556509887895),
 (486, 0.10206207261596573),
 (487, 0.07372097807744857),
 (488, 0.0397778642087865),
 (489, 0.041666666666666664),
 (490, 0.07905694150420947),
 (491, 0.04767312946227961),
 (492, 0.06565321642986127),
 (493, 0.04082482904638629),
 (494, 0.0),
 (495, 0.0753778361444409),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0753778361444409),
 (499, 0.031750031750047626),
 (500, 0.029880715233359837),
 (501, 0.06904309634237427),
 (502, 0.026958193300859603),
 (503, 0.08718572905786445),
 (504, 0.035355339059327376),
 (505, 0.07715167498104596),
 (506, 0.0),
 (507, 0.07086833868923009),
 (508, 0.12126781251816646),
 (509, 0.0808745799025788),
 (510, 0.027607881518711633),
 (511, 0.10022296571715913),
 (512, 0.031750031750047626),
 (513, 0.06154574548966637),
 (514, 0.09374999999999997),
 (515, 0.0),
 (516, 0.0),
 (517, 0.023014365447458086),
 (518, 0.058123819371909635),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.05455447255899809),
 (524, 0.03466876226407682),
 (525, 0.026064301757134343),
 (526, 0.0),
 (527, 0.0),
 (528, 0.025253813613805264),
 (529, 0.027277236279499045),
 (530, 0.07071067811865475),
 (531, 0.05270462766947299),
 (532, 0.0),
 (533, 0.036860489038724284),
 (534, 0.044194173824159216),
 (535, 0.057353933467640436),
 (536, 0.026958193300859603),
 (537, 0.07372097807744857),
 (538, 0.0),
 (539, 0.06063390625908323),
 (540, 0.05892556509887895),
 (541, 0.04811252243246881),
 (542, 0.042257712736425826),
 (543, 0.10910894511799618),
 (544, 0.09525009525014289),
 (545, 0.029880715233359837),
 (546, 0.0753778361444409),
 (547, 0.09374999999999997),
 (548, 0.0),
 (549, 0.07819290527140303),
 (550, 0.0),
 (551, 0.04682929057908469),
 (552, 0.0),
 (553, 0.03340765523905304),
 (554, 0.03227486121839514),
 (555, 0.01733438113203841),
 (556, 0.030316953129541614),
 (557, 0.030316953129541614),
 (558, 0.0),
 (559, 0.034020690871988585),
 (560, 0.04856429311786321),
 (561, 0.03857583749052298),
 (562, 0.0),
 (563, 0.057353933467640436),
 (564, 0.035355339059327376),
 (565, 0.04811252243246881),
 (566, 0.07819290527140303),
 (567, 0.0),
 (568, 0.06063390625908323),
 (569, 0.10101525445522105),
 (570, 0.039528470752104736),
 (571, 0.022821773229381916),
 (572, 0.08908708063747478),
 (573, 0.0236227795630767),
 (574, 0.02551551815399144),
 (575, 0.029880715233359837),
 (576, 0.06063390625908323),
 (577, 0.06454972243679027),
 (578, 0.05050762722761053),
 (579, 0.03227486121839514),
 (580, 0.026352313834736494),
 (581, 0.10206207261596575),
 (582, 0.05050762722761053),
 (583, 0.13638618139749523),
 (584, 0.053300179088902604),
 (585, 0.0),
 (586, 0.04767312946227961),
 (587, 0.11180339887498948),
 (588, 0.0),
 (589, 0.05157106231293967),
 (590, 0.036860489038724284),
 (591, 0.05455447255899809),
 (592, 0.05661385170722978),
 (593, 0.0),
 (594, 0.058123819371909635),
 (595, 0.05661385170722978),
 (596, 0.10101525445522105),
 (597, 0.06063390625908323),
 (598, 0.0),
 (599, 0.017589938618257295),
 (600, 0.05050762722761053),
 (601, 0.03857583749052298),
 (602, 0.0472455591261534),
 (603, 0.059761430466719674),
 (604, 0.07071067811865475),
 (605, 0.0),
 (606, 0.0),
 (607, 0.09365858115816939),
 (608, 0.0),
 (609, 0.049999999999999996),
 (610, 0.06338656910463873),
 (611, 0.026064301757134343),
 (612, 0.07426106572325056),
 (613, 0.039528470752104736),
 (614, 0.031750031750047626),
 (615, 0.03466876226407682),
 (616, 0.03857583749052298),
 (617, 0.029061909685954818),
 (618, 0.10314212462587934),
 (619, 0.05892556509887895),
 (620, 0.0),
 (621, 0.036860489038724284),
 (622, 0.02321191727213148),
 (623, 0.04856429311786321),
 (624, 0.08333333333333333),
 (625, 0.0),
 (626, 0.030316953129541614),
 (627, 0.12166606584807188),
 (628, 0.053916386601719206),
 (629, 0.026064301757134343),
 (630, 0.026650089544451302),
 (631, 0.028676966733820218),
 (632, 0.0),
 (633, 0.049999999999999996),
 (634, 0.059761430466719674),
 (635, 0.026064301757134343),
 (636, 0.029880715233359837),
 (637, 0.0),
 (638, 0.0),
 (639, 0.027277236279499045),
 (640, 0.053916386601719206),
 (641, 0.0),
 (642, 0.032826608214930636),
 (643, 0.08385254915624211),
 (644, 0.06063390625908323),
 (645, 0.10101525445522105),
 (646, 0.059761430466719674),
 (647, 0.0),
 (648, 0.0),
 (649, 0.1178511301977579),
 (650, 0.0),
 (651, 0.02795084971874737),
 (652, 0.0),
 (653, 0.042874646285627205),
 (654, 0.07024393586862704),
 (655, 0.027277236279499045),
 (656, 0.0),
 (657, 0.05856516070822727),
 (658, 0.05661385170722978),
 (659, 0.05661385170722978),
 (660, 0.07216878364870323),
 (661, 0.06629126073623882),
 (662, 0.0),
 (663, 0.0),
 (664, 0.10206207261596575),
 (665, 0.07819290527140303),
 (666, 0.05455447255899809),
 (667, 0.0),
 (668, 0.07372097807744857),
 (669, 0.0),
 (670, 0.0),
 (671, 0.02830692585361489),
 (672, 0.030316953129541614),
 (673, 0.0),
 (674, 0.026958193300859603),
 (675, 0.053916386601719206),
 (676, 0.06933752452815364),
 (677, 0.028676966733820218),
 (678, 0.06565321642986127),
 (679, 0.0),
 (680, 0.029462782549439476),
 (681, 0.0),
 (682, 0.0),
 (683, 0.053916386601719206),
 (684, 0.0),
 (685, 0.039528470752104736),
 (686, 0.035355339059327376),
 (687, 0.062499999999999986),
 (688, 0.0),
 (689, 0.05590169943749474),
 (690, 0.030772872744833184),
 (691, 0.10606601717798213),
 (692, 0.0),
 (693, 0.0),
 (694, 0.07426106572325056),
 (695, 0.07216878364870323),
 (696, 0.045267873021259265),
 (697, 0.08964214570007951),
 (698, 0.04950737714883371),
 (699, 0.0),
 (700, 0.03227486121839514),
 (701, 0.0),
 (702, 0.05103103630798288),
 (703, 0.0),
 (704, 0.025785531156469834),
 (705, 0.026650089544451302),
 (706, 0.027277236279499045),
 (707, 0.03857583749052298),
 (708, 0.026650089544451302),
 (709, 0.04642383454426296),
 (710, 0.04682929057908469),
 (711, 0.10400628679223047),
 (712, 0.026650089544451302),
 (713, 0.0),
 (714, 0.0),
 (715, 0.11058146711617285),
 (716, 0.07372097807744857),
 (717, 0.049029033784546004),
 (718, 0.024282146558931603),
 (719, 0.041666666666666664),
 (720, 0.0),
 (721, 0.03466876226407682),
 (722, 0.024753688574416854),
 (723, 0.0),
 (724, 0.05455447255899809),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03812464258315116),
 (728, 0.05270462766947299),
 (729, 0.0),
 (730, 0.08058229640253801),
 (731, 0.08603090020146065),
 (732, 0.05521576303742327),
 (733, 0.0),
 (734, 0.07905694150420949),
 (735, 0.026064301757134343),
 (736, 0.03466876226407682),
 (737, 0.05590169943749474),
 (738, 0.07715167498104596),
 (739, 0.04055535528269063),
 (740, 0.05521576303742327),
 (741, 0.06154574548966637),
 (742, 0.036084391824351615),
 (743, 0.026958193300859603),
 (744, 0.07071067811865475),
 (745, 0.09847982464479191),
 (746, 0.09095085938862485),
 (747, 0.04950737714883371),
 (748, 0.039528470752104736),
 (749, 0.0),
 (750, 0.053300179088902604),
 (751, 0.0),
 (752, 0.025785531156469834),
 (753, 0.030772872744833184),

In [38]:
# It will give index of given movie 

new_df[new_df['title'] == 'The Lego Movie'].index[0]

744

In [45]:
# It will give the sorted list of movie which is similar to given movie

sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x: x[1])[1:6]

[(539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (260, 0.25110592822973776),
 (1216, 0.24944382578492943),
 (507, 0.2484646732989441)]

In [39]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

In [40]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan

In [46]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Ender's Game
Aliens vs Predator: Requiem
Independence Day

In [48]:
recommend('John Carter')

Star Trek: Insurrection
Mission to Mars
Captain America: The First Avenger
Escape from Planet Earth
Ghosts of Mars

In [41]:
import pickle

In [42]:
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))